import clsx from "clsx";

export default function ContentsContainer() {
  return (
    <div
      className={clsx(
        "flex-[1] flex-wrap rounded-md bg-black700 p-5",
        "max-lg:rounded-xl"
      )}
    >
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
      <p>asdazsdfsdf</p>
    </div>
  );
}
